### ISSUE TITLE
Misleading

### ISSUE THREAD

**Issue by kmlawson** [github/learn.github.com#1]
Hi there, I would recommend making a few changes to your "Beginner" line of learning offerings in order to make it a real "Beginner" line of learning offerings, at least to change the initial presentation.

Like perhaps 90% of resources out there on git,  your very first video, part one introduction to git that claims to explain "what git is" doesn't really do that but makes a lot of assumptions.

You assume:

1) The viewer already knows what versioning is, why it is in important, and what things like "commit" or "checkout" or other versioning terminology is.

2) You assume viewers know what SVN is, that they care whether or not git is smaller and faster, and how to use it. This is the problem with almost all the tutorials and introductions to git out there. It is like there is a massive insecurity complex (which given git's advantages, hardly seems necessary) on behalf of git developers that they seem to want to spent all their time on beginner introductions explaining how much cooler git is than SVN and other versioning solutions. 

I recommend moving the initial presentation to a "Introduction to Git for Programmers Who Are Familiar with SVN or Versioning"

and then create a real introduction to git to begin your series.

Alternatively, you can open with a paragraph on the page and prior to the movies on the prerequisites for the beginner offerings, that is to say, familiarity with versioning and SVN.

Respectfully,

Konrad M. Lawson

**Comment by matthewmccullough** [comment]
This is great input @kmlawson. We'll definitely bear in mind these important points you raise as we rebuild this video series.
