### ISSUE TITLE
Missing navigation on log page

### ISSUE THREAD

**Issue by sheerun** [github/learn.github.com#10]
I don't see "next" link on log page. Is that right?

**Comment by matthewmccullough** [comment]
http://learn.github.com/p/log.html

**Comment by sheerun** [comment]
Yup, that one.

**Comment by randomecho** [comment]
The list of pages in `episodes.yaml` lists **log** ("Git History") as the last page of the "Learn Git" section. 

So there wouldn't be a "next" to jump to.

**Comment by sheerun** [comment]
there are 15 pages in pages dir. i understand they're not ready?

**Comment by randomecho** [comment]
Looks like one of the missing, http://learn.github.com/p/undoing.html exists as published/live/200 OK. 

Can only guess those that aren't in the episodes list were just streamlined out.

**Comment by matthewmccullough** [comment]
@randomecho @sheerun These pages all need a little love to get them ready for "prime time".  I think they've just languished for a while. Any effort to get them in a useful state would be appreciated though. I'm thinking of setting aside some time in December to make that happen if no one beats me to it.

**Comment by brntbeer** [comment]
Closing this since it's now been fixed!
