### ISSUE TITLE
Add DNS entry to re-connect learn.github.com

### ISSUE THREAD

**Issue by matthewmccullough** [github/learn.github.com#12]
The learn.github.com content was brought from a separate `learn` account under the github account umbrella. The CNAME file is in place to route to this content, but a DNS entry is needed via the @github/ops team to have this content showing up once again.

It is fully realized that the index is an instant redirect to gitref.org, but the other content still has some links to it on the web that we don't want to break.

**Comment by matthewmccullough** [comment]
@github/training-team Just FYI guys that this was moved from the `learn` account on GitHub under the `github` account, but now needs DNS to get it back live.

**Comment by jnewland** [comment]
Actually, DNS is all set, it needs pages built. Under the learn account, a repo called `learn.github.com` is a User pages repo, but under the GitHub account it's just a normal repo and needs content to be pushed to the gh-pages branch like so:

https://help.github.com/articles/user-organization-and-project-pages

**Comment by ShepAlderson** [comment]
@jnewland github.github.com/learn.github.com redirects to http://gitref.org/

I pushed the gh-pages branch and included the CNAME file, but I don't know if this is going to work.

One issue with pages is that it requires the above long address. "learn.github.com" alone won't work, unless we setup redirection to hit it properly.

**Comment by jnewland** [comment]
Pages just rebuilt the CNAME map file. Looks good to me?

**Comment by ShepAlderson** [comment]
Redirect in a script in the index.html, has @jnewland pointed out to me in campfire. :facewall:

**Comment by matthewmccullough** [comment]
Yup. Knew that. But that's Scott C's doing a while ago as the history shows. The other content is still there and can be displayed. But just not by browsing to the domain name, but rather to the specific content. I'd like to re-use some of the content here in our offerings. Many things on the web still link to the old pages and I broke them with the move of the repo. Mea culpa.

**Comment by ShepAlderson** [comment]
@matthewmccullough I think that, if we want this to be a real portal, we start from scratch and build it up nicely. I'm all for using stuff from the past, but I'd love for "learn.github.com" to be a portal where people can come and, well, learn.

I'd also like the same for teach.github.com, to provide access to good stuff for people to use for their teaching.

**Comment by matthewmccullough** [comment]
Yup. Re-use in the sense of some of the modular lessons. Not look, feel, nor organization for the reasons you noted.

**Comment by matthewmccullough** [comment]
I've deleted the `master` branch and the `two` branch and changed the default page to gh-pages via the admin page for clarity.
