### ISSUE TITLE
Blip.tv videos no longer online

### ISSUE THREAD

**Issue by randomecho** [github/learn.github.com#26]
The videos sitting pretty up top on [Intro](http://learn.github.com/p/intro.html) and [Setup](http://learn.github.com/p/setup.html) are no longer with us. 

> Sorry, this episode is no longer available.

Pour one out. :baby_bottle: 

Should they just be removed or are there replacements?

**Comment by matthewmccullough** [comment]
Blip.tv is on a purging spree of anything that isn't TV-like.  But not to fear!  I've preserved all of them for posterity's sake up on http://youtube.com/github .

Just a matter of finding the matching YouTube URLs...  :)  No small task, I know...  And then embedding them.

**Comment by randomecho** [comment]
[Git-SCM Git Basics #1 - What is VCS?](http://www.youtube.com/watch?v=hKfo0OXc1BI) seems like it fits for Intro, but not certain any other video in the YouTube account so far fits for Setup.

**Comment by matthewmccullough** [comment]
I think http://www.youtube.com/watch?v=Esl439M154M is C1 and http://www.youtube.com/watch?v=cPlsn96n1d8 is a good setup one.

**Comment by randomecho** [comment]
Agreed on the second, but do prefer your "Git-SCM Git Basics 1 - What is VCS?" video as it does provide a clear overview of just what the whole Git thing is and why it's even used.

**Comment by matthewmccullough** [comment]
Yes actually. Nice suggestion.  Yup.
