### ISSUE TITLE
Homepage is either handcrafted cogs or raked with template

### ISSUE THREAD

**Issue by randomecho** [github/learn.github.com#29]
As hinted at #28 the homepage on the live learn.github.com site is as below

![Handcraftiness - artefacts for show, fo sho](https://f.cloud.github.com/assets/743877/113403/2720a368-6b53-11e2-903d-b2427a775858.png)

But if you `rake`, the following is generated:

![raked up - needs heavy jpeg compression next time](https://f.cloud.github.com/assets/743877/113404/272e07a6-6b53-11e2-83aa-c208606748bb.png)

What you don't see on the second screenshot is the GitHub tutorial section, which for now are just stubs of article headers and descriptions.

Which landing page is correct-er on this site?

**Comment by matthewmccullough** [comment]
The hand drawn index is definitely more correct, but was knowingly and
embarrassingly just "crammed in" without regards to the make file. I
think the index should no longer be generated. But shouldn't the other
pages be "right?"

**Comment by randomecho** [comment]
The pages under /p that are rake generated do look right. 

It was just a concern that the visual cue from the sketch cogs to the rest of the site may be a little off because it is so drastic, not sharing the same theme as the others try in line with the rest of the training materials and sites.

**Comment by matthewmccullough** [comment]
@randomecho Definitely agreed. The part I was hoping was that a GitHub employed designer would see "where" we wanted to go with the cogs and update it to reflect that navigational idea, but in the GitHub:Training styled blue that I wanted teach.github.com and learn.github.com to share for the time being.  That never seemed to happen. ;)  So for now, the data in the hand-crafted index is more correct.  The other pages we should just merge in, if they are right as you say.  I'll go merge that.

**Comment by brntbeer** [comment]
Also wondering if this should close now because the site is generated with Jekyll

**Comment by randomecho** [comment]
Nubbing out rake seems to make this a moot point since the only page that will be around is bedazzled in cogs.
