### ISSUE TITLE
Analytics Not Tracking

### ISSUE THREAD

**Issue by matthewmccullough** [github/learn.github.com#41]
I logged into the GitHub Google Analytics site, but it seems that http://learn.github.com/p/index.html URL tracking stopped around March 10th.  The tracking code still looks correct to my untrained-eye, so I need some @github/cream team help.

```
  <script>
  var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
  document.write(unescape("%3Cscript src='" + gaJsHost + "google-analytics.com/ga.js' type='text/javascript'%3E%3C/script%3E"));
  var pageTracker = _gat._getTracker("UA-3769691-2");
  pageTracker._initData();
  pageTracker._trackPageview();
  </script>
```

The code above is what's in the page now.

This was brought up as a part of https://github.com/github/github-universe/issues/10#issuecomment-16253751

**Comment by randomecho** [comment]
The only real difference between what you have now and what was there a while back is blocking the JavaScript in two sections instead of the current one:

```
<script>
var gaJsHost = (("https:" == document.location.protocol) ? "https://ssl." : "http://www.");
document.write( ... );
</script>
<script>
var pageTracker = _gat._getTracker("UA-3769691-2");
pageTracker._initData();
pageTracker._trackPageview();
</script>
```

Don't know if that's the exact problem though.

**Comment by matthewmccullough** [comment]
Closing this because we're going to collapse this site into Training as well.

CC: @jordanmccullough
