### ISSUE TITLE
Collapse site content into training.github.com

### ISSUE THREAD

**Issue by matthewmccullough** [github/learn.github.com#52]
Like @jordanmccullough's effort to [fold teach into training](https://github.com/github/training.github.com/pull/140) for easier discovery of learning content in one unified site, we should also collapse learn.github.com into training.github.com through a merge of as much content as we can to preserve authorship info, and then a 301 redirect to the training.github.com domain of an equivalent URL.

**Comment by jordanmccullough** [comment]
The PR for this on training.github.com has been [opened here](https://github.com/github/training.github.com/pull/147). Closing this now in favor of pending PR approval.
