### ISSUE TITLE
Have a little issue on github dashboard

### ISSUE THREAD

**Issue by mickaelandrieu** [github/learn.github.com#53]
Sorry for this report here, but I don't know where exactly report this.

![issue](https://f.cloud.github.com/assets/1247388/1851086/573240c0-76e2-11e3-9df1-e2790814c62e.PNG)

As you can see, I have a little typo on my dashboard.

Regards,

**Comment by matthewmccullough** [comment]
Hi @mickaelandrieu.  Thanks for reporting it.  If you can drop this same report over into an email to support@github.com the developers of that module can see it right away.  Cheers!

**Comment by mickaelandrieu** [comment]
Done. Have a nice day matthew !
